"""tambah unique constraint pada nik

Revision ID: 0645e69fbbb6
Revises: 
Create Date: 2026-05-15 21:30:33.211578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0645e69fbbb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riwayat', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nik'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riwayat', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
