"""add tanggal lahir

Revision ID: 57194661ffa7
Revises: 0645e69fbbb6
Create Date: 2026-05-15 23:54:10.218031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57194661ffa7'
down_revision = '0645e69fbbb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riwayat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggal_lahir', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riwayat', schema=None) as batch_op:
        batch_op.drop_column('tanggal_lahir')

    # ### end Alembic commands ###
